run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - ineffassign
    - unused
    - gosimple
    - misspell
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false

output:
  formats:
    - format: line-number
      path: stdout